name: nyamnyam
description: "Dicoding Fundamental Flutter Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State management
  provider: ^6.1.2
  
  # HTTP client for API calls
  http: ^1.2.2
  
  # Custom fonts
  google_fonts: ^7.0.2
  
  # Navigation
  go_router: ^17.0.1
  
  # Local database
  sqflite: ^2.4.2
  path: ^1.9.1
  
  # Key-value storage
  shared_preferences: ^2.5.3
  
  # Notifications
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.0
  
  # Background tasks
  workmanager: ^0.9.0+3

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  
  # Testing
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/custom/app-icon.png"
  adaptive_icon_background: "#046D77"
  adaptive_icon_foreground: "assets/icons/custom/app-icon.png"

